version: '3'
services:
    mongo:
        image: mongo:4.4.0-bionic
        volumes:
            - ./data:/data/db
        # ports: 
            # - 27017:27017
        restart: always
    api:
        build: .
        ports: 
            - 8080:8080
        environment:
            - MONGO_HOST=mongodb://mongo:27017
            # - ACCESS_TOKEN=<some_access_token>
        restart: always
        depends_on: 
            - mongo
